### ISSUE TITLE
Crashes when resizing

### ISSUE THREAD

**Issue by dnut** [dnut/buffer.py#4]
```python
Traceback (most recent call last):
  File "/home/drew/coding/scripts/python/sync.py", line 99, in <module>
    inst.loop()
  File "/home/drew/coding/scripts/python/sync.py", line 88, in loop
    self.report_progress()
  File "/home/drew/coding/scripts/python/sync.py", line 63, in report_progress
    self.screen.addstr(5, 0, 'Writeback:      {:{}} kB'.format(self.sys.wback, 10))
_curses.error: addwstr() returned ERR
```

**Comment by dnut** [comment]
Resolved by: https://github.com/dnut/buffer.py/commit/75d44c8f417df0cf00d280551ce66e9be171df82
